# Generated by Django 4.2.11 on 2024-04-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='imagess',
        ),
    ]
