# Generated by Django 4.2.11 on 2024-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_audiofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
