# Generated by Django 4.2.11 on 2024-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadedfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mark', models.IntegerField()),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='student_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
