# Generated by Django 4.2.11 on 2024-04-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_marks_uploadedfiles_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.CharField(max_length=50),
        ),
    ]
