# Generated by Django 4.2.11 on 2024-04-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_marks_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
