# Generated by Django 4.2.11 on 2024-04-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mp4details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPTXDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pptx_file', models.FileField(upload_to='ppt/')),
            ],
        ),
    ]
